export class Setting {
    public static PAGE :any = {
        ELECTRICITY : "electricity",
        WATER : "water",
        PHONE : "phone",
        COMMUNICATE : "communicate",
        IT : "it",
        HEAVY_EQP:"heavyeqp",
        FIREBRIGADE : "firebrigade",
        GARBAGEDISPOSAL : "garbagedis",  
        CNDN : "cndn",
        POS : "pos",
    }
    public static FILEREQUEST :any = {
        REQ : "REQ",
        EDIT : "EDIT",
        CANCEL : "CANCEL",
    }
    public static ROLE :any = {
        ELECTRICITY : "ROLE_USER_ELECTRICITY",
        WATER : "ROLE_USER_WATER",
        TELEPHONE : "ROLE_USER_TELEPHONE",
        INTERCOM : "ROLE_USER_INTERCOM",
        IT : "ROLE_USER_IT",
        EQUIPMENT : "ROLE_USER_EQUIPMENT",
        GARBAGEDISPOSAL : "ROLE_USER_GARBAGEDISPOSAL",
        FIREBRIGADE : "ROLE_USER_FIREBRIGADE",
        COMMUNICATE : "ROLE_USER_COMMUNICATE",
        CNDN : "ROLE_USER_CNDN",
        POS : "ROLE_USER_POS",
        INFORMATION : "ROLE_USER_INFORMATION",
        SETTING : "ROLE_USER_SETTING",
        SETTING_DATA : "ROLE_USER_SETTING_DATA",
        APPROVE : "ROLE_APPROVER",
    };

    public static GL_MODULE_NAME :any = {
        ELECTRICITY_RATE_CHARGE : "ELECTRICITY_RATE_CHARGE",
        ELECTRICITY_CHARGE_TYPE : "ELECTRICITY_CHARGE_TYPE",

        
        WATER_CHARGE_RATES : "WATER_CHARGE_RATES",
        WATER_MAINTENANCE: "WATER_MAINTENANCE",
        WATER_INSURANCE_CHARGE : "WATER_INSURANCE_CHARGE",
        WATER_INSTALLATION_CHARGE : "WATER_INSTALLATION_CHARGE",
        WATER_MAINTENANCE_OTHER : "WATER_MAINTENANCE_OTHER",
        WATER_WASTE: "WATER_WASTE",


        PHONE_RATE_CHARGE : "PHONE_RATE_CHARGE",
        COMMUNICATE_TRANSCEIVER : "COMMUNICATE_TRANSCEIVER",
        COMMUNICATE_AIRLINE_LOGO : "COMMUNICATE_AIRLINE_LOGO",
        COMMUNICATE_FLIGHT_INFO : "COMMUNICATE_FLIGHT_INFO",
        COMMUNICATE_DISPLAY : "COMMUNICATE_DISPLAY",
        IT_NETWORK : "IT_NETWORK",
        IT_OTHER: "IT_OTHER",
        IT_CUTE_TRAINING: "IT_CUTE_TRAINING",
        IT_DEDICATED_CUTE: "IT_DEDICATED_CUTE",
        IT_STAFF_PUBLIC: "IT_STAFF_PUBLIC",
        HEAVY_EQP:"HEAVY_EQP",
        FIREBRIGADE : "FIREBRIGADE",
        GARBAGEDISPOSAL : "GARBAGEDISPOSAL",  
        CNDN : "CNDN",
        POS : "POS",
    }
}